from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

from trading_engine.backtest.models import (
    Fill,
    Order,
    OrderSide,
)


@dataclass(slots=True, frozen=True)
class MarketEvent:
    """New market-data snapshot."""

    timestamp: datetime
    prices: dict[str, float]


@dataclass(slots=True, frozen=True)
class SignalEvent:
    """Trading signal generated by a strategy."""

    symbol: str
    side: OrderSide
    quantity: float
    timestamp: datetime


@dataclass(slots=True)
class OrderEvent:
    """Order submitted to the execution pipeline."""

    order: Order


@dataclass(slots=True, frozen=True)
class FillEvent:
    """Completed execution produced by the execution model."""

    fill: Fill
