from __future__ import annotations

import numpy as np
import pandas as pd

from trading_engine.indicators._validation import (
    validate_numeric_series,
    validate_positive_series,
)


def simple_returns(prices: pd.Series) -> pd.Series:
    """Calculate arithmetic returns.

    R_t = P_t / P_{t-1} - 1
    """
    validate_positive_series(prices, name="Prices")

    result = prices.pct_change(fill_method=None)
    result.name = "simple_return"

    return result


def log_returns(prices: pd.Series) -> pd.Series:
    """Calculate continuously compounded returns.

    r_t = ln(P_t / P_{t-1})
    """
    validate_positive_series(prices, name="Prices")

    result = np.log(prices / prices.shift(1))
    result.name = "log_return"

    return result


def cumulative_returns(returns: pd.Series) -> pd.Series:
    """Convert arithmetic periodic returns into cumulative returns.

    C_t = product(1 + R_i) - 1
    """
    validate_numeric_series(
        returns,
        name="Returns",
        allow_nan=True,
    )

    if (returns.dropna() < -1).any():
        raise ValueError("Arithmetic returns cannot be less than -100%.")

    result = (1.0 + returns.fillna(0.0)).cumprod() - 1.0
    result.name = "cumulative_return"

    return result


def wealth_index(
    returns: pd.Series,
    initial_capital: float = 1.0,
) -> pd.Series:
    """Calculate portfolio wealth generated by periodic returns."""
    if not isinstance(initial_capital, (int, float)):
        raise TypeError("Initial capital must be numeric.")

    if initial_capital <= 0:
        raise ValueError("Initial capital must be greater than zero.")

    cumulative = cumulative_returns(returns)

    result = initial_capital * (1.0 + cumulative)
    result.name = "wealth"

    return result
