from __future__ import annotations

import numpy as np
import pandas as pd


def _validate_prices(prices: pd.Series) -> None:
    """Validate a price series used by return calculations."""
    if not isinstance(prices, pd.Series):
        raise TypeError("Prices must be a pandas Series.")

    if prices.empty:
        raise ValueError("Prices cannot be empty.")

    if not pd.api.types.is_numeric_dtype(prices):
        raise TypeError("Prices must contain numeric values.")

    if prices.isna().any():
        raise ValueError("Prices cannot contain missing values.")

    if not np.isfinite(prices.to_numpy(dtype=float)).all():
        raise ValueError("Prices must contain only finite values.")

    if (prices <= 0).any():
        raise ValueError("Prices must be strictly positive.")


def simple_returns(prices: pd.Series) -> pd.Series:
    """Calculate arithmetic returns.

    R_t = P_t / P_{t-1} - 1
    """
    _validate_prices(prices)

    result = prices.pct_change(fill_method=None)
    result.name = "simple_return"

    return result


def log_returns(prices: pd.Series) -> pd.Series:
    """Calculate continuously compounded returns.

    r_t = ln(P_t / P_{t-1})
    """
    _validate_prices(prices)

    result = np.log(prices / prices.shift(1))
    result.name = "log_return"

    return result


def cumulative_returns(returns: pd.Series) -> pd.Series:
    """Convert arithmetic periodic returns into cumulative returns.

    C_t = product(1 + R_i) - 1
    """
    if not isinstance(returns, pd.Series):
        raise TypeError("Returns must be a pandas Series.")

    if returns.empty:
        raise ValueError("Returns cannot be empty.")

    if not pd.api.types.is_numeric_dtype(returns):
        raise TypeError("Returns must contain numeric values.")

    if np.isinf(returns.to_numpy(dtype=float)).any():
        raise ValueError("Returns cannot contain infinite values.")

    if (returns.dropna() < -1).any():
        raise ValueError("Arithmetic returns cannot be less than -100%.")

    result = (1.0 + returns.fillna(0.0)).cumprod() - 1.0
    result.name = "cumulative_return"

    return result


def wealth_index(
    returns: pd.Series,
    initial_capital: float = 1.0,
) -> pd.Series:
    """Calculate portfolio wealth generated by periodic returns."""
    if not isinstance(initial_capital, (int, float)):
        raise TypeError("Initial capital must be numeric.")

    if initial_capital <= 0:
        raise ValueError("Initial capital must be greater than zero.")

    cumulative = cumulative_returns(returns)

    result = initial_capital * (1.0 + cumulative)
    result.name = "wealth"

    return result
